# Generated by Django 4.1.2 on 2022-11-17 10:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Currency', '0002_alter_currencyrate_date_history_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currencyrate',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 11, 17, 10, 13, 50, 923841, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='history',
            name='convert_date',
            field=models.DateField(default=datetime.datetime(2022, 11, 17, 10, 13, 50, 924126, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='history',
            name='currency_date',
            field=models.DateField(default=datetime.datetime(2022, 11, 17, 10, 13, 50, 924115, tzinfo=datetime.timezone.utc)),
        ),
        migrations.DeleteModel(
            name='HistoricalCurrencyRate',
        ),
    ]
