# Generated by Django 4.1.2 on 2022-11-18 11:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Currency', '0003_alter_currencyrate_date_alter_history_convert_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('url_address', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='currencyrate',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 11, 18, 11, 7, 39, 468144, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='history',
            name='convert_date',
            field=models.DateField(default=datetime.datetime(2022, 11, 18, 11, 7, 39, 468421, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='history',
            name='currency_date',
            field=models.DateField(default=datetime.datetime(2022, 11, 18, 11, 7, 39, 468412, tzinfo=datetime.timezone.utc)),
        ),
    ]
