# Generated by Django 4.1.2 on 2022-11-29 07:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Currency', '0004_menu_alter_currencyrate_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currencyrate',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 11, 29, 7, 47, 23, 859199, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='history',
            name='convert_date',
            field=models.DateField(default=datetime.datetime(2022, 11, 29, 7, 47, 23, 859476, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='history',
            name='currency_date',
            field=models.DateField(default=datetime.datetime(2022, 11, 29, 7, 47, 23, 859468, tzinfo=datetime.timezone.utc)),
        ),
    ]
