# Generated by Django 4.1.2 on 2022-11-29 10:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Currency', '0005_alter_currencyrate_date_alter_history_convert_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currencyrate',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 11, 29, 10, 16, 25, 356798, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='history',
            name='convert_date',
            field=models.DateField(default=datetime.datetime(2022, 11, 29, 10, 16, 25, 357086, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='history',
            name='currency_date',
            field=models.DateField(default=datetime.datetime(2022, 11, 29, 10, 16, 25, 357078, tzinfo=datetime.timezone.utc)),
        ),
    ]
