# Generated by Django 4.1.2 on 2022-11-29 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bitcoin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
                ('price', models.FloatField()),
                ('marketCap', models.CharField(max_length=100)),
                ('vwap24Hr', models.FloatField()),
                ('symbol', models.CharField(max_length=10)),
                ('supply', models.CharField(max_length=50)),
                ('volumeUsd24Hr', models.CharField(max_length=50)),
                ('changePercent24Hr', models.FloatField()),
                ('image_name', models.CharField(max_length=100)),
            ],
        ),
    ]
